#!/bin/bash
clear
slowdns () {
echo -e ""
    echo -e "================================="
    echo -e "     𝗣𝗔𝗡𝗘𝗟 𝗦𝗟𝗢𝗪𝗗𝗡𝗦 𝗠𝗔𝗡𝗔𝗚𝗘𝗥       "
    echo -e "================================="
    echo -e "\033[0;36m[01]\033[m | Install SlowDNS"
    echo -e "\033[0;36m[02]\033[m | Informasi Akun SlowDNS"
    echo -e "\033[0;36m[03]\033[m | Hentikan SlowDNS"
    echo -e "\033[0;36m[04]\033[m | Hapus SlowDNS"
    echo -e "\033[0;36m[05]\033[m | Install Ulang SlowDNS"
    echo -e "\033[0;36m[06]\033[m | Hapus Script SlowDNS"
    echo -e "\033[0;36m[00]\033[m | Keluar Panel"
    echo ""
    echo -ne "\033[0;36mKetik Ctrl + C Untuk Keluar VPS Dulu:\0033[m " && read option
    case $option in
    1) Option1 ;;
    2) Option2 ;;
    3) Option3 ;;
    4) Option4 ;;
    5) Option5 ;;
    6) Option6 ;;
    0) Sair ;;
    *) "Invalid option" ; echo ; slowdns ;;
    esac
    }

Option1 () {
    clear
    bash /etc/slowdns/slowdns-ssh
}


Option2 () {
    clear
    bash /etc/slowdns/slowdns-info
}

Option3 () {
    clear
    bash /etc/slowdns/startdns
}

Option4 () {
    clear
    bash /etc/slowdns/stopdns
}

Option5 () {
     clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
}

Option6 () {
     clear
    bash /etc/slowdns/remove-slow
    echo -e "\033[0;31mSlowDNS Manager Uninstalled!\033[0m"
    sleep 2
    rm /bin/slowdns
}

Sair() {
    clear
    exit
}
clear
slowdns
